# Generated by Django 4.0.3 on 2023-10-02 12:15

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crewNeckMen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_desc', models.CharField(max_length=500)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color')),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=15)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('M_R_P', models.DecimalField(decimal_places=2, max_digits=50)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('discount_price', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('prod_id', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('images', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
        migrations.CreateModel(
            name='DropCutMen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_desc', models.CharField(max_length=500)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color')),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=15)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('M_R_P', models.DecimalField(decimal_places=2, max_digits=50)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('discount_price', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('prod_id', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('images', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
        migrations.CreateModel(
            name='OversizedMen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_desc', models.CharField(max_length=500)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color')),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=15)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('M_R_P', models.DecimalField(decimal_places=2, max_digits=50)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('discount_price', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('prod_id', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('images', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
