# Generated by Django 4.0.3 on 2023-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_crewneckmen_prod_id_alter_dropcutmen_prod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewneckmen',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
