# Generated by Django 4.0.3 on 2023-10-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_crewneckmen_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropcutmen',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
