# Generated by Django 4.0.3 on 2023-10-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_crewneckmen_prod_id_alter_oversizedmen_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_neck', models.ManyToManyField(to='inventory.crewneckmen')),
                ('drop_cut', models.ManyToManyField(to='inventory.dropcutmen')),
                ('oversized', models.ManyToManyField(to='inventory.oversizedmen')),
            ],
        ),
    ]
