# Generated by Django 4.0.3 on 2023-10-03 06:42

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_men'),
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_name', models.CharField(max_length=100)),
                ('Design_id', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Themes', multiselectfield.db.fields.MultiSelectField(choices=[('Anime', 'Anime'), ('Drip and Doodle', 'Drip and Doodle'), ('Abstract', 'Abstract'), ('Music and Bands', 'Music and Bands'), ('Movies and Series', 'Movies and Series'), ('Typography', 'Typography'), ('Sports', 'Sports'), ('Marvel and DC', 'Marvel and DC'), ('Sanskriti', 'Sanskriti'), ('Persona', 'Persona')], max_length=500)),
                ('Men', models.ManyToManyField(to='inventory.men')),
            ],
        ),
    ]
