# Generated by Django 4.2.5 on 2023-10-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_imgall"),
    ]

    operations = [
        migrations.RemoveField(model_name="crewneckmen", name="images",),
        migrations.AddField(
            model_name="crewneckmen",
            name="images",
            field=models.ManyToManyField(to="inventory.imgall"),
        ),
    ]
