# Generated by Django 4.2.5 on 2023-10-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_remove_crewneckmen_images_crewneckmen_images"),
    ]

    operations = [
        migrations.RenameModel(old_name="imgall", new_name="crewNeckImg",),
    ]
