# Generated by Django 4.2.5 on 2023-10-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_rename_imgall_crewneckimg"),
    ]

    operations = [
        migrations.CreateModel(
            name="DropCutImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.ImageField(blank=True, null=True, upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="OversizedImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.ImageField(blank=True, null=True, upload_to="images/")),
            ],
        ),
    ]
