# Generated by Django 4.2.5 on 2023-10-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_dropcutimg_oversizedimg"),
    ]

    operations = [
        migrations.RemoveField(model_name="dropcutmen", name="images",),
        migrations.RemoveField(model_name="oversizedmen", name="images",),
        migrations.AddField(
            model_name="dropcutmen",
            name="images",
            field=models.ManyToManyField(to="inventory.dropcutimg"),
        ),
        migrations.AddField(
            model_name="oversizedmen",
            name="images",
            field=models.ManyToManyField(to="inventory.oversizedimg"),
        ),
    ]
