# Generated by Django 4.2.5 on 2023-10-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0013_remove_dropcutmen_images_remove_oversizedmen_images_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="crewneckwomen", name="images",),
        migrations.RemoveField(model_name="dropcutwomen", name="images",),
        migrations.RemoveField(model_name="oversizedwomen", name="images",),
        migrations.AddField(
            model_name="crewneckwomen",
            name="images",
            field=models.ManyToManyField(to="inventory.crewneckimg"),
        ),
        migrations.AddField(
            model_name="dropcutwomen",
            name="images",
            field=models.ManyToManyField(to="inventory.dropcutimg"),
        ),
        migrations.AddField(
            model_name="oversizedwomen",
            name="images",
            field=models.ManyToManyField(to="inventory.oversizedimg"),
        ),
    ]
